/**
 * Individual profile (section 8): Layer 0 scores with plain-language summaries, the user's own
 * CSI-16 and RDAS, PSDQ profile if applicable, and the user's own tags. No partner data.
 * Two labels at the top: which items are validated instrument scores (with citations) and
 * which are generated, unvalidated content.
 */
import { INSTRUMENTS, isInstrumentKey } from "@/instruments/registry";
import type { Score } from "@/instruments/schema";

export const VALIDATED_LABEL = "Validated instrument scores. Each carries its instrument name and source citation.";
export const GENERATED_LABEL = "Generated by the interpreter; not validated. Plain-language sentences and any derived content.";

export type ProfileContent = {
  labels: { validated: string; generated: string };
  generated_at: string;
  validated_scores: Array<{
    instrument_key: string;
    name: string;
    source_citation: string;
    license_note: string;
    subscale: string;
    value: number;
    cutoff_label: string | null;
    unvalidated: boolean;
  }>;
  generated_sentences: Array<{ instrument_key: string; sentence: string }>;
  tags: Array<{ domain: string; item_ref: string; tag: "requirement" | "preference"; comment: string }>;
  contains_partner_data: false;
};

const PROFILE_INSTRUMENTS = new Set(["mini_ipip", "ecr_r", "phq9", "gad7", "sis_ses_sf", "sdi2", "oci_r", "csi16", "rdas", "psdq_sf"]);

export function buildProfile(input: {
  ownScores: Score[];
  sentences: Array<{ instrument_key: string; sentence: string }>;
  tags: Array<{ domain: string; item_ref: string; tag: "requirement" | "preference"; comment: string }>;
  now?: Date;
}): ProfileContent {
  const validated_scores = input.ownScores
    .filter((s) => PROFILE_INSTRUMENTS.has(s.instrument_key) && isInstrumentKey(s.instrument_key))
    .map((s) => {
      const def = INSTRUMENTS[s.instrument_key as keyof typeof INSTRUMENTS].definition;
      return {
        instrument_key: s.instrument_key,
        name: def.name,
        source_citation: def.source_citation,
        license_note: def.license_note,
        subscale: s.subscale,
        value: s.value,
        cutoff_label: s.cutoff_label,
        unvalidated: def.unvalidated,
      };
    });
  return {
    labels: { validated: VALIDATED_LABEL, generated: GENERATED_LABEL },
    generated_at: (input.now ?? new Date()).toISOString(),
    validated_scores,
    generated_sentences: input.sentences.filter((s) => PROFILE_INSTRUMENTS.has(s.instrument_key)),
    tags: input.tags,
    contains_partner_data: false,
  };
}
