import { DECISION_SUPPORT_LABEL, FEATURES, SCREENER_HANDOFF_SENTENCE } from "@/config/features";
import * as data from "@/lib/data";
import type { ProfileContent } from "@/lib/profile/build";
import { requireUser } from "@/lib/supabase/server";

const MH = new Set(["phq9", "gad7", "oci_r"]);

/**
 * Therapist view (section 11a). Visible only to a clinician with an active, revocable link
 * granted by the subject. Every read is logged with the consent state at the time.
 */
export default async function ClinicianSubjectPage({ params }: { params: Promise<{ subjectId: string }> }) {
  const { subjectId } = await params;
  const user = await requireUser();
  const result = await data.profileForClinician({ clinicianUserId: user.id, subjectUserId: subjectId });
  if (!result) {
    return (
      <div className="space-y-6">
        <h1 className="text-2xl font-semibold">No access</h1>
        <p className="mt-2">This person has not granted you access, or has revoked it.</p>
      </div>
    );
  }
  const profile = (result.profile?.content ?? null) as ProfileContent | null;
  const subject = await data.getUser(subjectId);
  const coupleId = result.profile?.couple_id ?? null;
  const sentiment = coupleId ? await data.sentimentFlagsForClinician({ clinicianUserId: user.id, subjectUserId: subjectId, coupleId }) : [];

  return (
    <div className="space-y-8">
      <header>
        <h1 className="text-2xl font-semibold">Clinician view: {subject?.display_name ?? "subject"}</h1>
        <p className="mt-1 text-sm">Every access to this view is logged with the consent state at the time. Access ends the moment the person revokes it.</p>
      </header>

      {profile ? (
        <section aria-labelledby="scores">
          <h2 id="scores" className="text-lg font-semibold">
            Validated instrument scores
          </h2>
          <p className="text-sm">{profile.labels.validated}</p>
          <ul className="mt-2 space-y-1">
            {profile.validated_scores.map((s) => (
              <li key={`${s.instrument_key}:${s.subscale}`}>
                <span className="font-medium">{s.name}</span>
                {s.unvalidated ? " (unvalidated)" : ""}, {s.subscale}: {s.value}
                {s.cutoff_label ? ` (${s.cutoff_label.replace(/_/g, " ")})` : " (no published cutoff)"}
                {MH.has(s.instrument_key) ? ` — ${SCREENER_HANDOFF_SENTENCE}` : ""}
                <span className="block text-xs">Source: {s.source_citation}</span>
              </li>
            ))}
          </ul>
          <h3 className="mt-4 font-semibold">Plain-language summaries</h3>
          <p className="text-sm">{profile.labels.generated}</p>
          <ul className="mt-2 list-disc pl-5">
            {profile.generated_sentences.map((s) => (
              <li key={s.instrument_key}>{s.sentence}</li>
            ))}
          </ul>
        </section>
      ) : (
        <p>No profile has been generated yet.</p>
      )}

      <section aria-labelledby="support" className="rounded border p-4">
        <h2 id="support" className="text-lg font-semibold">
          Decision support
        </h2>
        <p className="text-sm italic">{DECISION_SUPPORT_LABEL}</p>
        <h3 className="mt-3 font-semibold">Sentiment markers (written answers)</h3>
        {!FEATURES.sentiment_flagger ? (
          <p className="text-sm">The sentiment flagger is disabled until it passes the hand-coded evaluation set.</p>
        ) : sentiment.length === 0 ? (
          <p className="text-sm">No markers recorded.</p>
        ) : (
          <ul className="mt-2 space-y-2">
            {sentiment.map((f) => (
              <li key={f.id} className="text-sm">
                <span className="font-medium">{f.marker.replace(/_/g, " ")}</span> (confidence {f.confidence.toFixed(2)}): “{f.quoted_span}”
                <span className="block text-xs">{DECISION_SUPPORT_LABEL}</span>
              </li>
            ))}
          </ul>
        )}
        <h3 className="mt-3 font-semibold">Risk indicators</h3>
        <p className="text-sm">Disabled until a validation study exists. An indicator without a validation cohort, an effect size and a confidence interval cannot be displayed.</p>
      </section>

      {result.briefs.length > 0 ? (
        <section aria-labelledby="briefs">
          <h2 id="briefs" className="text-lg font-semibold">
            Couple brief (both partners consented)
          </h2>
          <p className="text-sm">Generated by the interpreter; not validated.</p>
          <ul className="mt-2 list-disc pl-5">
            {result.briefs.map((b) => (
              <li key={b.id}>{b.domain.replace(/_/g, " ")}</li>
            ))}
          </ul>
        </section>
      ) : null}
    </div>
  );
}
