/**
 * lib/profile/build and lib/export/markdown: the individual profile (own data only, two labels)
 * and the Markdown / HTML exports with the "generated by the interpreter; not validated." label
 * and the instrument source citations.
 */
import { describe, expect, it } from "vitest";
import { INSTRUMENTS } from "@/instruments/registry";
import type { Score } from "@/instruments/schema";
import type { ParentingLines, PlanItem } from "@/lib/data/brief_plan";
import { briefMarkdown, GENERATED_LABEL, markdownToHtml, planMarkdown, profileMarkdown, scoreLine } from "@/lib/export/markdown";
import type { BriefDomain } from "@/lib/llm/schemas";
import { buildProfile, GENERATED_LABEL as PROFILE_GENERATED_LABEL, VALIDATED_LABEL } from "@/lib/profile/build";

const score = (instrument_key: string, subscale: string, value: number, cutoff_label: string | null = null, extra: Partial<Score> = {}): Score => ({
  instrument_key,
  subscale,
  value,
  cutoff_label,
  scoring_version: "1.0.0",
  ...extra,
});

const ownScores: Score[] = [
  score("mini_ipip", "extraversion", 3.5),
  score("ecr_r", "anxiety", 3.1),
  score("phq9", "total", 12, "moderate"),
  score("csi16", "total", 70, "non_distressed"),
  score("psdq_sf", "authoritative", 4.2),
  score("cpq_sf", "self_demand_partner_withdraw", 3),
  score("made_up", "total", 1),
];

const sentences = [
  { instrument_key: "phq9", sentence: "Your PHQ-9 total is 12, in the moderate range. Screener result; clinical evaluation required." },
  { instrument_key: "cpq_sf", sentence: "A CPQ sentence that does not belong in the profile." },
];
const tags = [{ domain: "household", item_ref: "household_t3", tag: "requirement" as const, comment: "Ask before moving my things." }];
const now = new Date("2026-09-15T12:00:00.000Z");

describe("buildProfile", () => {
  const profile = buildProfile({ ownScores, sentences, tags, now });

  it("includes only the profile instruments with name, citation and license", () => {
    expect(profile.validated_scores.map((s) => s.instrument_key)).toEqual(["mini_ipip", "ecr_r", "phq9", "csi16", "psdq_sf"]);
    const csi = profile.validated_scores.find((s) => s.instrument_key === "csi16")!;
    expect(csi).toEqual({
      instrument_key: "csi16",
      name: INSTRUMENTS.csi16.definition.name,
      source_citation: INSTRUMENTS.csi16.definition.source_citation,
      license_note: INSTRUMENTS.csi16.definition.license_note,
      subscale: "total",
      value: 70,
      cutoff_label: "non_distressed",
      unvalidated: false,
    });
    for (const s of profile.validated_scores) {
      expect(s.source_citation.length).toBeGreaterThan(0);
      expect(s.license_note.length).toBeGreaterThan(0);
    }
  });

  it("carries both labels, the generated sentences for profile instruments only, the tags, and no partner data", () => {
    expect(profile.labels).toEqual({ validated: VALIDATED_LABEL, generated: PROFILE_GENERATED_LABEL });
    expect(profile.labels.validated).toContain("Validated instrument scores");
    expect(profile.labels.generated).toContain("Generated by the interpreter; not validated");
    expect(profile.generated_sentences).toEqual([sentences[0]]);
    expect(profile.tags).toEqual(tags);
    expect(profile.contains_partner_data).toBe(false);
    expect(profile.generated_at).toBe("2026-09-15T12:00:00.000Z");
    expect(JSON.stringify(profile)).not.toMatch(/partner_b|cpq_sf|made_up/);
  });
});

describe("scoreLine", () => {
  it("names the instrument, the cutoff and the source", () => {
    const line = scoreLine(score("csi16", "total", 70, "non_distressed"));
    expect(line).toBe(`- ${INSTRUMENTS.csi16.definition.name}, total: 70 (non distressed). Source: ${INSTRUMENTS.csi16.definition.source_citation}`);
    expect(scoreLine(score("ecr_r", "anxiety", 3.1))).toContain("(no published cutoff)");
    expect(scoreLine(score("polarization", "gap", 2, null, { unvalidated: true }))).toContain(" (unvalidated), gap: 2");
    expect(scoreLine(score("made_up", "x", 1))).toBe("- made_up, x: 1 (no published cutoff). Source: ");
  });
});

describe("planMarkdown", () => {
  const items: PlanItem[] = [
    { domain: "household", topic: "Moving things", agreed: "Ask first.", a_does: "Asks.", b_does: "Waits.", revisit_date: null, status: "active", a_tag: "requirement", b_tag: "requirement", pinned: true },
    { domain: "household", topic: "Dishes", agreed: "Alternate\ndays.", a_does: "Mon/Wed", b_does: "Tue/Thu", revisit_date: "2030-01-15", status: "active", pinned: false },
    { domain: "parenting", topic: "Bedtime", agreed: "8pm on school nights.", a_does: "Reads.", b_does: "Brushes.", revisit_date: null, status: "parked", pinned: false },
  ];
  const parentingLines: ParentingLines = {
    children_questioning_adults: "Yes, respectfully.",
    who_corrects_and_how: "Whoever is present.",
    structure_vs_freedom: "Structured mornings.",
    language_and_modeling_standard: "No swearing.",
    adults_disagreeing_in_front_of_child: "Pause, discuss later.",
  };
  const md = planMarkdown({ coupleLabel: "A and B", version: 3, items, parentingLines, generatedAt: now });

  it("carries the version, the label, the pinned section, a table per domain and the parenting lines", () => {
    expect(md).toContain("# Our plan, version 3");
    expect(md).toContain("A and B. 2026-09-15.");
    expect(md).toContain(GENERATED_LABEL);
    expect(GENERATED_LABEL).toBe("generated by the interpreter; not validated.");
    expect(md).toContain("## Shared requirements (settled)\n- **Moving things**: Ask first.");
    expect(md).toContain("## household\n\n| Topic | What we agreed | A does | B does | Revisit | Status |\n|---|---|---|---|---|---|\n| Dishes | Alternate days. | Mon/Wed | Tue/Thu | 2030-01-15 | active |");
    expect(md).toContain("| Bedtime | 8pm on school nights. | Reads. | Brushes. |  | parked |");
    expect(md).toContain("### The five parenting lines\n- **Children questioning adults**: Yes, respectfully.");
    expect(md).toContain("- **The protocol for adults disagreeing in front of the child**: Pause, discuss later.");
  });

  it("omits the pinned section and the parenting lines when absent", () => {
    const plain = planMarkdown({ coupleLabel: "A and B", version: 1, items: items.slice(1, 2), parentingLines: null, generatedAt: now });
    expect(plain).not.toContain("Shared requirements");
    expect(plain).not.toContain("parenting lines");
  });
});

describe("briefMarkdown", () => {
  const brief: BriefDomain = {
    domain: "household",
    what_each_would_do: { a: "Ask first.", b: "Just do it." },
    values_underneath: { a: "Being consulted.", b: "Momentum." },
    tags_side_by_side: [{ item_ref: "each other's things", a_tag: "requirement", a_comment: "Ask.", b_tag: "preference", b_comment: null }],
    perception_gaps: [{ item_ref: "household chores", a_explanation: "more than noticed", b_explanation: "about even" }],
    polarization_loops: [{ dimension: "order in the home", shared_pattern: "One tidies more as the other relaxes (unvalidated).", unvalidated: true }],
    consistency_notes: [{ user: "a", note: "Weekdays only." }],
    aligned_items: ["cooking"],
    parked_items: ["money"],
  };
  const md = briefMarkdown({ coupleLabel: "A and B", briefs: [brief, { ...brief, domain: "parenting", aligned_items: ["cooking", "bedtime"], parked_items: [] }], generatedAt: now });

  it("labels all content as generated and lists aligned, parked and each domain", () => {
    expect(md).toContain(`_All content below is ${GENERATED_LABEL}_`);
    expect(md).toContain("## Aligned\n- cooking\n- bedtime\n");
    expect(md).toContain("## Parked on purpose\n- money\n");
    expect(md).toContain("## household\n");
    expect(md).toContain("## parenting\n");
    expect(md).toContain("**What each would do.** A: Ask first. B: Just do it.");
    expect(md).toContain("| Item | A | B |\n|---|---|---|\n| each other's things | requirement Ask. | preference  |");
    expect(md).toContain("- Perception gap, household chores: A sees more than noticed B sees about even");
    expect(md).toContain("- Shared pattern (polarization block, unvalidated), order in the home: One tidies more as the other relaxes (unvalidated).");
    expect(md).toContain("- Note (A): Weekdays only.");
  });
});

describe("profileMarkdown", () => {
  const profile = buildProfile({ ownScores, sentences, tags, now });
  const md = profileMarkdown({ displayName: "Dana", profile });

  it("carries both labels, the source citation on every score, the generated section and the no-partner-data note", () => {
    expect(md).toContain("# Individual profile: Dana");
    expect(md).toContain(`**Validated:** ${VALIDATED_LABEL}`);
    expect(md).toContain(`**Generated:** ${PROFILE_GENERATED_LABEL}`);
    expect(md).toContain(`## Plain-language summaries (${GENERATED_LABEL})`);
    for (const s of profile.validated_scores) expect(md).toContain(`Source: ${s.source_citation}`);
    expect(md).toContain(`- ${INSTRUMENTS.phq9.definition.name}, total: 12 (moderate). Source: ${INSTRUMENTS.phq9.definition.source_citation}`);
    expect(md).toContain(`- ${INSTRUMENTS.ecr_r.definition.name}, anxiety: 3.1 (no published cutoff).`);
    expect(md).toContain("- Your PHQ-9 total is 12, in the moderate range.");
    expect(md).toContain("## Your tags\n- household, household_t3: requirement. Ask before moving my things.");
    expect(md.trimEnd().endsWith("_This profile contains no partner data._")).toBe(true);
  });
});

describe("markdownToHtml", () => {
  it("renders headings, paragraphs, lists and tables, with inline bold and italics, and escapes < and &", () => {
    const md = [
      "# Title <one>",
      "## Section & more",
      "### Sub",
      "Paragraph with **bold** and _italic_ and 1 < 2.",
      "- item one",
      "- item <two>",
      "",
      "| A | B |",
      "|---|---|",
      "| x | y & z |",
      "",
      "Tail.",
    ].join("\n");
    const html = markdownToHtml(md, "My <title>");
    expect(html.startsWith("<!doctype html><html><head><meta charset=\"utf-8\"><title>My &lt;title></title>")).toBe(true);
    expect(html).toContain("<h1>Title &lt;one></h1>");
    expect(html).toContain("<h2>Section &amp; more</h2>");
    expect(html).toContain("<h3>Sub</h3>");
    expect(html).toContain("<p>Paragraph with <strong>bold</strong> and <em>italic</em> and 1 &lt; 2.</p>");
    expect(html).toContain("<ul>\n<li>item one</li>\n<li>item &lt;two></li>\n</ul>");
    expect(html).toContain("<table>\n<tr><th>A</th><th>B</th></tr>\n<tr><td>x</td><td>y &amp; z</td></tr>\n</table>");
    expect(html).toContain("<p>Tail.</p>");
    expect(html).not.toContain("|---|");
    expect(html.trimEnd().endsWith("</body></html>")).toBe(true);
  });

  it("closes an open list or table at the end of the document", () => {
    expect(markdownToHtml("- a\n- b", "t")).toContain("<ul>\n<li>a</li>\n<li>b</li>\n</ul>");
    expect(markdownToHtml("| h |\n|---|\n| v |", "t")).toContain("<table>\n<tr><th>h</th></tr>\n<tr><td>v</td></tr>\n</table>");
  });

  it("round-trips the generated plan and brief documents without leaking raw Markdown table syntax", () => {
    const plan = planMarkdown({
      coupleLabel: "A and B",
      version: 1,
      items: [{ domain: "household", topic: "Dishes", agreed: "Alternate.", a_does: "M", b_does: "T", revisit_date: null, status: "active" }],
      parentingLines: null,
      generatedAt: now,
    });
    const html = markdownToHtml(plan, "Plan");
    expect(html).toContain("<h1>Our plan, version 1</h1>");
    expect(html).toContain("<tr><th>Topic</th><th>What we agreed</th><th>A does</th><th>B does</th><th>Revisit</th><th>Status</th></tr>");
    expect(html).toContain("<tr><td>Dishes</td><td>Alternate.</td><td>M</td><td>T</td><td></td><td>active</td></tr>");
    expect(html).toContain(`<em>Agenda items were written by the couple. Any summaries they were drawn from are ${GENERATED_LABEL}</em>`);
    expect(html).not.toMatch(/\|---/);
  });
});
