/**
 * Markdown exports (section 7, 8). Instrument scores are labeled by source; all derived content
 * is labeled "generated by the interpreter; not validated." The PDF is rendered from the HTML
 * version of the same Markdown in inngest/export.ts.
 */
import { INSTRUMENTS, isInstrumentKey } from "@/instruments/registry";
import type { Score } from "@/instruments/schema";
import type { BriefDomain } from "@/lib/llm/schemas";
import type { PlanItem, ParentingLines } from "@/lib/data/brief_plan";
import type { ProfileContent } from "@/lib/profile/build";
import { PARENTING_LINES } from "@/lib/plan/rules";

export const GENERATED_LABEL = "generated by the interpreter; not validated.";

function esc(s: string | null | undefined): string {
  return (s ?? "").replace(/\r?\n/g, " ").trim();
}

export function scoreLine(s: Score): string {
  const def = isInstrumentKey(s.instrument_key) ? INSTRUMENTS[s.instrument_key].definition : null;
  const name = def?.name ?? s.instrument_key;
  const src = def?.source_citation ?? "";
  const tag = def?.unvalidated ? " (unvalidated)" : "";
  return `- ${name}${tag}, ${s.subscale}: ${s.value}${s.cutoff_label ? ` (${s.cutoff_label.replace(/_/g, " ")})` : " (no published cutoff)"}. Source: ${src}`;
}

export function planMarkdown(input: { coupleLabel: string; version: number; items: PlanItem[]; parentingLines: ParentingLines | null; generatedAt?: Date }): string {
  const lines: string[] = [];
  lines.push(`# The Plan, version ${input.version}`);
  lines.push("");
  lines.push(`${input.coupleLabel}. ${(input.generatedAt ?? new Date()).toISOString().slice(0, 10)}.`);
  lines.push("");
  lines.push(`_Agenda items were written by the couple. Any summaries they were drawn from are ${GENERATED_LABEL}_`);
  lines.push("");
  const pinned = input.items.filter((i) => i.pinned);
  if (pinned.length) {
    lines.push("## Shared requirements (settled)");
    for (const it of pinned) lines.push(`- **${esc(it.topic)}**: ${esc(it.agreed)}`);
    lines.push("");
  }
  const domains = [...new Set(input.items.filter((i) => !i.pinned).map((i) => i.domain))];
  for (const d of domains) {
    lines.push(`## ${d.replace(/_/g, " ")}`);
    lines.push("");
    lines.push("| Topic | What we agreed | A does | B does | Revisit | Status |");
    lines.push("|---|---|---|---|---|---|");
    for (const it of input.items.filter((i) => !i.pinned && i.domain === d)) {
      lines.push(`| ${esc(it.topic)} | ${esc(it.agreed)} | ${esc(it.a_does)} | ${esc(it.b_does)} | ${it.revisit_date ?? ""} | ${it.status} |`);
    }
    lines.push("");
    if (d === "parenting" && input.parentingLines) {
      lines.push("### The five parenting lines");
      for (const l of PARENTING_LINES) lines.push(`- **${l.label}**: ${esc(input.parentingLines[l.key])}`);
      lines.push("");
    }
  }
  return lines.join("\n");
}

export function briefMarkdown(input: { coupleLabel: string; briefs: BriefDomain[]; generatedAt?: Date }): string {
  const lines: string[] = [];
  lines.push("# Brief");
  lines.push("");
  lines.push(`${input.coupleLabel}. ${(input.generatedAt ?? new Date()).toISOString().slice(0, 10)}. _All content below is ${GENERATED_LABEL}_`);
  lines.push("");
  const aligned = [...new Set(input.briefs.flatMap((b) => b.aligned_items))];
  if (aligned.length) {
    lines.push("## Aligned");
    for (const a of aligned) lines.push(`- ${esc(a)}`);
    lines.push("");
  }
  const parked = [...new Set(input.briefs.flatMap((b) => b.parked_items))];
  if (parked.length) {
    lines.push("## Parked on purpose");
    for (const p of parked) lines.push(`- ${esc(p)}`);
    lines.push("");
  }
  for (const b of input.briefs) {
    lines.push(`## ${b.domain.replace(/_/g, " ")}`);
    lines.push("");
    lines.push(`**What each would do.** A: ${esc(b.what_each_would_do.a)} B: ${esc(b.what_each_would_do.b)}`);
    lines.push("");
    lines.push(`**Values underneath.** A: ${esc(b.values_underneath.a)} B: ${esc(b.values_underneath.b)}`);
    lines.push("");
    if (b.tags_side_by_side.length) {
      lines.push("| Item | A | B |");
      lines.push("|---|---|---|");
      for (const t of b.tags_side_by_side) lines.push(`| ${esc(t.item_ref)} | ${t.a_tag ?? ""} ${esc(t.a_comment)} | ${t.b_tag ?? ""} ${esc(t.b_comment)} |`);
      lines.push("");
    }
    for (const g of b.perception_gaps) lines.push(`- Perception gap, ${esc(g.item_ref)}: A sees ${esc(g.a_explanation)} B sees ${esc(g.b_explanation)}`);
    for (const l of b.polarization_loops) lines.push(`- Shared pattern (polarization block, unvalidated), ${esc(l.dimension)}: ${esc(l.shared_pattern)}`);
    for (const n of b.consistency_notes) lines.push(`- Note (${n.user.toUpperCase()}): ${esc(n.note)}`);
    lines.push("");
  }
  return lines.join("\n");
}

export function profileMarkdown(input: { displayName: string; profile: ProfileContent }): string {
  const lines: string[] = [];
  lines.push(`# Individual profile: ${input.displayName}`);
  lines.push("");
  lines.push(`**Validated:** ${input.profile.labels.validated}`);
  lines.push("");
  lines.push(`**Generated:** ${input.profile.labels.generated}`);
  lines.push("");
  lines.push("## Validated instrument scores");
  for (const s of input.profile.validated_scores) {
    lines.push(`- ${s.name}${s.unvalidated ? " (unvalidated)" : ""}, ${s.subscale}: ${s.value}${s.cutoff_label ? ` (${s.cutoff_label.replace(/_/g, " ")})` : " (no published cutoff)"}. Source: ${s.source_citation}`);
  }
  lines.push("");
  lines.push(`## Plain-language summaries (${GENERATED_LABEL})`);
  for (const s of input.profile.generated_sentences) lines.push(`- ${esc(s.sentence)}`);
  lines.push("");
  if (input.profile.tags.length) {
    lines.push("## Your tags");
    for (const t of input.profile.tags) lines.push(`- ${t.domain}, ${esc(t.item_ref)}: ${t.tag}. ${esc(t.comment)}`);
    lines.push("");
  }
  lines.push("_This profile contains no partner data._");
  return lines.join("\n");
}

/** Minimal Markdown to HTML for PDF rendering: headings, paragraphs, lists, tables, bold, italics. */
export function markdownToHtml(md: string, title: string): string {
  const out: string[] = [];
  const lines = md.split("\n");
  let inTable = false;
  let inList = false;
  const inline = (s: string) =>
    s
      .replace(/&/g, "&amp;")
      .replace(/</g, "&lt;")
      .replace(/\*\*(.+?)\*\*/g, "<strong>$1</strong>")
      .replace(/_(.+?)_/g, "<em>$1</em>");
  for (const raw of lines) {
    const line = raw.trimEnd();
    if (line.startsWith("|")) {
      const cells = line.split("|").slice(1, -1).map((c) => c.trim());
      if (cells.every((c) => /^-+$/.test(c))) continue;
      if (!inTable) {
        out.push("<table>");
        inTable = true;
        out.push(`<tr>${cells.map((c) => `<th>${inline(c)}</th>`).join("")}</tr>`);
      } else {
        out.push(`<tr>${cells.map((c) => `<td>${inline(c)}</td>`).join("")}</tr>`);
      }
      continue;
    }
    if (inTable) {
      out.push("</table>");
      inTable = false;
    }
    if (line.startsWith("- ")) {
      if (!inList) {
        out.push("<ul>");
        inList = true;
      }
      out.push(`<li>${inline(line.slice(2))}</li>`);
      continue;
    }
    if (inList) {
      out.push("</ul>");
      inList = false;
    }
    const h = /^(#{1,3})\s+(.*)$/.exec(line);
    if (h) {
      out.push(`<h${h[1].length}>${inline(h[2])}</h${h[1].length}>`);
      continue;
    }
    if (line.trim()) out.push(`<p>${inline(line)}</p>`);
  }
  if (inList) out.push("</ul>");
  if (inTable) out.push("</table>");
  return `<!doctype html><html><head><meta charset="utf-8"><title>${inline(title)}</title><style>
body{font-family:Georgia,serif;font-size:11pt;line-height:1.4;margin:36px;color:#111}
h1{font-size:18pt;margin:0 0 6px}h2{font-size:13pt;margin:16px 0 4px}h3{font-size:11pt;margin:10px 0 2px}
table{border-collapse:collapse;width:100%;font-size:9.5pt}th,td{border:1px solid #999;padding:3px 5px;vertical-align:top;text-align:left}
ul{margin:4px 0 8px 18px;padding:0}li{margin:2px 0}em{color:#444}
</style></head><body>${out.join("\n")}</body></html>`;
}
