import { currentUser } from "@/lib/supabase/server";
import { Card } from "@/app/_components/Card";
import { PageHeader } from "@/app/_components/PageHeader";
import { LinkButton } from "@/app/_components/Button";
import { APP_NAME } from "@/lib/brand";

export default async function LandingPage() {
  const user = await currentUser();
  return (
    <div className="space-y-6">
      <PageHeader
        title={APP_NAME}
        lede="Two people answer the same questions separately. Each sees their own results first. Only then do you read one brief together and write a plan you both keep."
      />
      <Card>
        <h2 className="text-lg font-semibold">How it works</h2>
        <ol className="list-decimal ml-5 mt-2 space-y-1">
          <li>Set up together: names, who sees what, and when each of you will sit down.</li>
          <li>Each of you, alone: Layer 0 (about yourself) and Layer 1 (about the relationship). Save and return any time.</li>
          <li>Nothing is compared until both of you are done. Each of you reads your own results privately first.</li>
          <li>Where something flagged, a few written questions, one domain at a time, still alone.</li>
          <li>Then the brief and the plan, together, one domain per sitting, with dates to look again.</li>
        </ol>
        <div className="mt-4 flex flex-wrap gap-3">
          {user ? <LinkButton href="/setup">Continue to setup</LinkButton> : <LinkButton href="/sign-in">Sign in</LinkButton>}
          <LinkButton href="/square-one" variant="secondary">
            Square One (before a relationship)
          </LinkButton>
        </div>
      </Card>
      <Card>
        <h2 className="text-lg font-semibold">What it is not</h2>
        <p className="mt-2 text-sm">
          No screen here says whether two people should stay together or names anything about a person. Instrument scores are
          labelled with the instrument they came from. Anything written by the interpreter is labelled &ldquo;generated by the
          interpreter; not validated.&rdquo;
        </p>
      </Card>
    </div>
  );
}
