export function Card({ children, className = "", as: Tag = "section" }: { children: React.ReactNode; className?: string; as?: "section" | "div" | "article" }) {
  return <Tag className={`rounded-lg border border-border bg-surface p-4 sm:p-5 ${className}`}>{children}</Tag>;
}

/** Fixed label for anything the interpreter wrote. Used on every derived section. */
export function GeneratedLabel({ className = "" }: { className?: string }) {
  return <p className={`text-xs uppercase tracking-wide text-muted ${className}`}>generated by the interpreter; not validated.</p>;
}

export function UnvalidatedLabel() {
  return <span className="ml-1 rounded border border-warn-border bg-warn-bg px-1.5 py-0.5 text-xs">unvalidated</span>;
}
