/**
 * A card on the desk: paper surface, thin rule, faint shadow. With `eyebrow`, a small label sits
 * above the content.
 */
export function Card({
  children,
  className = "",
  as: Tag = "section",
  eyebrow,
  dashed = false,
}: {
  children: React.ReactNode;
  className?: string;
  as?: "section" | "div" | "article" | "li";
  eyebrow?: React.ReactNode;
  dashed?: boolean;
}) {
  return (
    <Tag className={`rounded-card border border-rule bg-surface p-5 shadow-card ${dashed ? "border-dashed shadow-none" : ""} ${className}`}>
      {eyebrow ? <p className="eyebrow mb-3">{eyebrow}</p> : null}
      {children}
    </Tag>
  );
}

/** Fixed label for anything the interpreter wrote. Used on every derived section. */
export function GeneratedLabel({ className = "" }: { className?: string }) {
  return <p className={`eyebrow ${className}`}>generated by the interpreter; not validated.</p>;
}

export function UnvalidatedLabel() {
  return <span className="ml-1 rounded-full border border-warn bg-warn-bg px-2 py-0.5 align-middle font-sans text-xs font-medium tracking-wide">unvalidated</span>;
}

/** A small status chip: the accent for what matters most, quiet for the rest. */
export function Chip({ children, tone = "quiet" }: { children: React.ReactNode; tone?: "accent" | "quiet" }) {
  const cls = tone === "accent" ? "bg-tint text-accent" : "border border-rule text-muted";
  return <span className={`inline-block whitespace-nowrap rounded-full px-2.5 py-1 font-sans text-xs font-medium tracking-wide ${cls}`}>{children}</span>;
}
