/**
 * User-facing vocabulary, in one place. The build prompt's names (Layer 0, Layer 1, instruments,
 * color layer, domains, weights, interpreter) stay in code and config; people see these words.
 */
import type { Domain } from "@/instruments/schema";

/** Fixed label on anything the model wrote. Replaces the build prompt's "generated by the interpreter; not validated." */
export const GENERATED_NOTE = "Written by the app from your answers. Not a validated result.";

export const SCORES_NOTE = "Scores come from published questionnaires and carry the questionnaire's name and source.";

export const PART_TITLES = {
  layer0: "Part 1: About you",
  layer1: "Part 2: About the two of you",
} as const;

export const DOMAIN_TITLES: Record<Domain, string> = {
  parenting: "Parenting",
  intimacy: "Intimacy and affection",
  communication: "Communication",
  conflict: "Conflict and repair",
  household: "Household",
  self_care: "Self-care and health",
  social_family_longterm: "Friends, family, and the long term",
};

/** Plain words for how much a topic came up, from its rank in the list. */
export function topicEmphasis(rank: number): { label: string; tone: "accent" | "quiet" } {
  return rank === 0 ? { label: "Most to discuss", tone: "accent" } : { label: "Worth discussing", tone: "quiet" };
}
