import * as data from "@/lib/data";
import { BriefDomainSchema, type BriefDomain } from "@/lib/llm/schemas";
import { parseProfile } from "@/app/_lib/results";
import { Card, UnvalidatedLabel } from "@/app/_components/Card";
import { PageHeader } from "@/app/_components/PageHeader";
import { BriefSections } from "@/app/brief/_components/BriefSections";

/** Public therapist view. Resolving the token logs the access; nothing here needs a sign-in. */
export default async function SharePage({ params }: { params: Promise<{ token: string }> }) {
  const { token } = await params;
  const resolved = token.length >= 16 && token.length <= 200 ? await data.resolveTherapistShare(token) : null;
  const profile = resolved?.profile?.content ? parseProfile(resolved.profile.content) : null;
  if (!resolved || !profile) {
    return (
      <div className="space-y-6">
        <PageHeader title="Shared profile" />
        <Card>
          <p role="alert">This link is no longer valid.</p>
        </Card>
      </div>
    );
  }
  const owner = await data.getUser(resolved.share.user_id);
  const briefs: BriefDomain[] = resolved.briefs.map((b) => BriefDomainSchema.safeParse(b.content)).filter((r) => r.success).map((r) => r.data);
  const members = resolved.share.couple_id ? await data.listCoupleUsers(resolved.share.couple_id) : [];
  const names = { a: members.find((m) => m.side === "a")?.display_name ?? "A", b: members.find((m) => m.side === "b")?.display_name ?? "B" };

  return (
    <div className="space-y-6">
      <PageHeader title={`Individual profile: ${owner?.display_name ?? "shared"}`} lede="Shared by its owner for a limited time. Screener results are not diagnoses; clinical evaluation is required." />
      <Card>
        <p className="text-sm">
          <strong>Validated:</strong> {profile.labels.validated}
        </p>
        <p className="mt-1 text-sm">
          <strong>Generated:</strong> {profile.labels.generated}
        </p>
      </Card>
      <Card>
        <h2 className="text-lg font-semibold">Validated instrument scores</h2>
        <div className="mt-3 overflow-x-auto">
          <table className="w-full text-sm">
            <thead>
              <tr>
                <th scope="col">Instrument</th>
                <th scope="col">Subscale</th>
                <th scope="col">Value</th>
                <th scope="col">Cutoff</th>
                <th scope="col">Source</th>
              </tr>
            </thead>
            <tbody>
              {profile.validated_scores.map((s) => (
                <tr key={`${s.instrument_key}:${s.subscale}`}>
                  <td>
                    {s.name}
                    {s.unvalidated ? <UnvalidatedLabel /> : null}
                  </td>
                  <td>{s.subscale.replace(/_/g, " ")}</td>
                  <td>{Number.isInteger(s.value) ? s.value : s.value.toFixed(2)}</td>
                  <td>{s.cutoff_label ? s.cutoff_label.replace(/_/g, " ") : "no published cutoff"}</td>
                  <td className="text-xs">{s.source_citation}</td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </Card>
      <Card>
        <h2 className="text-lg font-semibold">Plain-language sentences</h2>
        <p className="text-xs uppercase tracking-wide text-muted">generated by the interpreter; not validated.</p>
        <ul className="mt-3 list-disc space-y-1 pl-5">
          {profile.generated_sentences.map((s) => (
            <li key={s.instrument_key}>{s.sentence}</li>
          ))}
        </ul>
      </Card>
      {profile.tags.length > 0 ? (
        <Card>
          <h2 className="text-lg font-semibold">Tags</h2>
          <ul className="mt-2 space-y-1 text-sm">
            {profile.tags.map((t) => (
              <li key={`${t.domain}:${t.item_ref}`}>
                <span className="text-muted">{t.domain.replace(/_/g, " ")}, {t.item_ref}:</span> {t.tag}. {t.comment}
              </li>
            ))}
          </ul>
        </Card>
      ) : null}
      <p className="text-sm italic">This profile contains no partner data.</p>
      {briefs.length > 0 ? (
        <>
          <h2 className="text-xl font-semibold">Couple brief (shared with both partners&rsquo; consent)</h2>
          <BriefSections briefs={briefs} names={names} />
        </>
      ) : null}
      <footer className="border-t border-border pt-3 text-sm text-muted">Every access to this link is logged.</footer>
    </div>
  );
}
